config/routes.rb
# require 'sidekiq/web'
Rails.application.routes.draw do
  get 'errors/show'

  root :to => 'posts#index'
  # mount Sidekiq::Web => '/sidekiq'

  scope '/api' do
    resources :comments, only: [:create, :update, :destroy]
    resources :replies, only: [:create, :update, :destroy]
    namespace :forum do
      resources :topics, only: [:create, :update, :destroy]
    end
  end
  resources :posts

  resources :categories do
    resources :posts
  end

  get '/forum', to: 'forum/categories#index'
  namespace :forum do
    resources :categories, only: [:index, :show, :create, :new, :update] do
      resources :topics, only: [:index, :show, :create, :new, :update]  do
        resources :replies, only: [:index, :show, :create, :new, :update]
      end
    end
  end
  resources :users
  devise_for :users, :path => '/auth'
  scope '/json' do
    post '/settings', :to => 'application#set_forum_collapse', :as => 'forum_settings'
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show]
      resources :comments, only: [:index, :show]
    end
  end
  get '/categories/:id', to: 'categories#show', :as => 'blog_category'
  get '/categories/:category_id/:id', to: 'posts#show', :as => 'blog_post'
  get '/forums', to: 'forum/categories#index', :as => 'forums_index'
  get '/forums/:id', to: 'forum/categories#show', :as => 'forums_category'
  get '/forums/:category_id/:id', to: 'forum/topics#show', :as => 'forums_topic'
end

app/models/post.rb
class Post < ActiveRecord::Base
  include PublicActivity::Model
  tracked

  validates_presence_of :title, :body, :user, :category

  belongs_to :user
  belongs_to :category
  has_many :comments
  accepts_nested_attributes_for :comments
  acts_as_url :title, :url_attribute => :slug
  def to_param
    slug
  end
end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
  def index
    @page_title = I18n.t('fog.fe.layout.nav.home')
    @posts = Post.includes(:category, :user).order(:created_at => :desc).frontend_page params[:page]
  end

  def show
    @post = Post.includes(:user, :category).find_by_slug(params[:id])
    @page_title = "#{@post.category.title} | #{@post.title}"
    @comments = Comment.includes(:user).where(:post_id => @post.id).frontend_page params[:comments_page]
    respond_to do |format|
      format.js
      format.json
      format.html
    end
  end

  private

    def post_params
      params.require(:post).permit(:title, :slug, :body, :user_id, :is_published, :comment)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/partials/_post.html.haml
.block.block-drop-shadow.post-entry{:id => "post-#{post.id}"}
  .head.bg-cubs
    %h2= link_to post.title, category_post_path(post.category, post)
    .pull-right
      %span.icon-calendar-empty
      = l post.created_at, :format => :short
    .head-subtitle
      %span.post-category
        %span.icon-list
        = link_to post.category.title, category_path(post.category)
      \&nbsp;
      %span.post-user
        %span.icon-user
        = link_to post.user.name, user_path(post.user)
  .content.typhography
    = post.body.split('<!--readmore-->')[0].html_safe

app/views/posts/partials/_post_show.html.haml
.head.bg-cubs
  %h2= @post.title
  .pull-right
    %span.icon-calendar-empty
    = l @post.created_at, :format => :short
  .head-subtitle
    %span.post-category
      %span.icon-list
      = link_to @post.category.title, category_path(@post.category)
    \&nbsp;
    %span.post-user
      %span.icon-user
      = link_to @post.user.name, user_path(@post.user)
.content.typhography
  = @post.body.html_safe

app/views/posts/partials/_post_show_comments.html.haml
- @comments.each do |comment|
  %div{:class => "messages-item #{'inbox' if user_signed_in? and current_user.id != comment.user.id}", :id => "message-#{comment.id}"}
    %a{ :href => user_path(comment.user), :class => 'message-user tipb', :data => { :original => { :title => comment.user.decorate.processed_name} }}
      = image_tag comment.user.decorate.processed_avatar, :class => 'img-round img-thumbnail', :width => 36
    .messages-item-text
      .messages-item-meta
      = comment.body.bbcode_to_html.html_safe
      .clearfix
    .messages-item-date
      = l comment.created_at, :format => :short