config/routes.rb
# require 'sidekiq/web'
Rails.application.routes.draw do
  get 'errors/show'

  root :to => 'posts#index'
  # mount Sidekiq::Web => '/sidekiq'

  scope '/api' do
    resources :comments, only: [:create, :update, :destroy]
    resources :replies, only: [:create, :update, :destroy]
    namespace :forum do
      resources :topics, only: [:create, :update, :destroy]
    end
  end
  resources :posts

  resources :categories do
    resources :posts
  end

  get '/forum', to: 'forum/categories#index'
  namespace :forum do
    resources :categories, only: [:index, :show, :create, :new, :update] do
      resources :topics, only: [:index, :show, :create, :new, :update]  do
        resources :replies, only: [:index, :show, :create, :new, :update]
      end
    end
  end
  resources :users
  devise_for :users, :path => '/auth'
  scope '/json' do
    post '/settings', :to => 'application#set_forum_collapse', :as => 'forum_settings'
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show]
      resources :comments, only: [:index, :show]
    end
  end
  get '/categories/:id', to: 'categories#show', :as => 'blog_category'
  get '/categories/:category_id/:id', to: 'posts#show', :as => 'blog_post'
  get '/forums', to: 'forum/categories#index', :as => 'forums_index'
  get '/forums/:id', to: 'forum/categories#show', :as => 'forums_category'
  get '/forums/:category_id/:id', to: 'forum/topics#show', :as => 'forums_topic'
end

app/models/forum.rb
module Forum
  def self.table_name_prefix
    'forum_'
  end
end

app/models/forum/category.rb
class Forum::Category < ActiveRecord::Base
  include PublicActivity::Model
  tracked
  extend ActsAsTree::TreeView
  extend ActsAsTree::TreeWalker
  belongs_to :user
  has_many :topics, :class_name => 'Forum::Topic'
  #has_one :last_post, :class_name => 'Forum::Reply'

  acts_as_tree order: 'title'
  acts_as_url :title, :url_attribute => :slug
  default_scope { order(:ordering => :asc) }
  def to_param
    slug
  end

  # def topic_count
  #   Forum::Topic.where(:category_id => self.self_and_descendants.map(&:id)).count
  #   #Forum::Topic.eager_load(:category).where(:category => self.self_and_descendants).count
  # end
  # def reply_count
  #   #Forum::Reply.where(:topic_id => Forum::Topic.where(:category_id => self.self_and_descendants.map(&:id)).pluck(:id)).count
  #   Forum::Reply.eager_load(:topic).where(:topic => Forum::Topic.eager_load(:category).where(:category => self.self_and_descendants)).count
  # end
  def last_post
    Forum::Reply.includes(:user, :topic).find(self.last_post_id)
  end
  # def last_post
  #   Forum::Reply.where(:topic_id => Forum::Topic.where(:category_id => self.self_and_descendants.map(&:id)).pluck(:id)).order(:created_at => :desc).first
  #   #Forum::Reply.eager_load(:topic).where(:topic => Forum::Topic.eager_load(:category).where(:category => self.self_and_descendants)).order(:created_at => :desc).first
  # end
end

app/models/forum/reply.rb
class Forum::Reply < ActiveRecord::Base
  include PublicActivity::Model
  after_create :update_parent_category
  tracked

  belongs_to :user
  #belongs_to :category, :class_name => 'Forum::Category', :inverse_of => :last_post
  belongs_to :topic, :class_name => 'Forum::Topic', :foreign_key => :topic_id

  default_scope { order(:created_at => :asc) }

  private
  def update_parent_category
    last_post = self
    topic = Forum::Topic.find(self.topic_id)
    cat = Forum::Category.find(topic.category_id)
    cat.self_and_ancestors.each do |entry|
      entry.reply_count += 1
      entry.last_post_id = last_post.id
      entry.save
    end
  end
end

app/models/forum/topic.rb
class Forum::Topic < ActiveRecord::Base
  include PublicActivity::Model
  tracked

  acts_as_url :title, :url_attribute => :slug
  default_scope { order(:updated_at => :desc) }

  belongs_to :user
  belongs_to :category, :class_name => 'Forum::Category'
  has_many :replies, :class_name => 'Forum::Reply'
  accepts_nested_attributes_for :replies

  validates_presence_of :title, :category, :user

  after_create :update_parent_category

  def to_param
    slug
  end

  private
  def update_parent_category
    Forum::Category.find(self.category.self_and_ancestors.map(&:id)).each do |cat|
      cat.topic_count += 1
      cat.save
    end
  end

end

app/controllers/forum/categories_controller.rb
class Forum::CategoriesController < ApplicationController
  before_action :set_forum_category, only: [:show, :edit, :update, :destroy]

  # GET /forum/categories
  # GET /forum/categories.json
  def index
    @page_title = I18n.t('fog.fe.layout.nav.forum')
    @forum_categories = Forum::Category.includes(children: [children: :children]).where(:parent_id => nil)
  end

  # GET /forum/categories/1
  # GET /forum/categories/1.json
  def show
    @page_title = "#{I18n.t('fog.fe.layout.nav.forum')} | #{@forum_category.title}"
    @topics = Forum::Topic.where(:category_id => @forum_category.id).frontend_page params[:page]
  end

  # GET /forum/categories/new
  def new
    @forum_category = Forum::Category.new
    @mapped_forum_categories = Forum::Category.walk_tree { |category, level| puts "#{'-'*level}#{category.title}"  }
  end

  # GET /forum/categories/1/edit
  def edit
  end

  # POST /forum/categories
  # POST /forum/categories.json
  def create
    @forum_category = Forum::Category.new(forum_category_params)

    respond_to do |format|
      if @forum_category.save
        format.html { redirect_to @forum_category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @forum_category }
      else
        format.html { render :new }
        format.json { render json: @forum_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forum/categories/1
  # PATCH/PUT /forum/categories/1.json
  def update
    respond_to do |format|
      if @forum_category.update(forum_category_params)
        format.html { redirect_to @forum_category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_category }
      else
        format.html { render :edit }
        format.json { render json: @forum_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum/categories/1
  # DELETE /forum/categories/1.json
  def destroy
    @forum_category.destroy
    respond_to do |format|
      format.html { redirect_to forum_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum_category
      @forum_category = Forum::Category.includes(:parent).find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_category_params
      params.require(:forum_category).permit(:title, :desc, :user_id, :parent_id, :is_published)
    end
end

app/controllers/forum/replies_controller.rb
class Forum::RepliesController < InheritedResources::Base

  private

    def reply_params
      params.require(:reply).permit(:title, :body, :is_published, :user_id, :topic_id)
    end
end

app/controllers/forum/topics_controller.rb
class Forum::TopicsController < ApplicationController
  before_action :set_forum_topic, only: [:show, :new, :edit, :update, :destroy]
  before_action :set_forum_category, only: [:new]

  # GET /forum/topics
  # GET /forum/topics.json
  def index
    @forum_topics = Forum::Topic.includes(:replies, :user).all
  end

  # GET /forum/topics/1
  # GET /forum/topics/1.json
  def show
    @page_title = "#{I18n.t('fog.fe.layout.nav.forum')} | #{@forum_topic.category.title} | #{@forum_topic.title}"
    @replies = Forum::Reply.includes(:user).where(:topic_id => @forum_topic.id).frontend_page params[:page]
  end

  # GET /forum/topics/new
  def new
    #@forum_topic = @forum_category.topics.new
    @forum_topic = Forum::Topic.new({:category_id => Forum::Category.find_by_slug(params[:category_id]).id})
    @forum_topic.replies.build
  end

  # GET /forum/topics/1/edit
  def edit
  end

  # POST /forum/topics
  # POST /forum/topics.json
  def create
    @forum_topic = Forum::Topic.new(forum_topic_params)
    respond_to do |format|
      if @forum_topic.save
        format.html { redirect_to forum_category_topic_path(@forum_topic.category, @forum_topic), notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @forum_topic }
      else
        format.html { render :new }
        format.json { render json: @forum_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forum/topics/1
  # PATCH/PUT /forum/topics/1.json
  def update
    respond_to do |format|
      if @forum_topic.update(forum_topic_params)
        format.html { redirect_to @forum_topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @forum_topic }
      else
        format.html { render :edit }
        format.json { render json: @forum_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forum/topics/1
  # DELETE /forum/topics/1.json
  def destroy
    @forum_topic.destroy
    respond_to do |format|
      format.html { redirect_to forum_topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_forum_category
    @forum_category = Forum::Category.find_by_slug(params[:category_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_forum_topic
    @forum_topic = Forum::Topic.includes(:category).find_by_slug(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def forum_topic_params
    params.require(:forum_topic).permit(:title, :category_id, :user_id, replies_attributes: [:user_id, :title, :body])
  end
end

app/helpers/forum/categories_helper.rb
module Forum::CategoriesHelper
  def form_parent_select
    @nested_values = []
    Forum::Category.walk_tree { |category, level| @nested_values.push(["#{'-'*level}#{category.title}", category.id]) }
    @nested_values
  end
  def topic_count(category)
    unless category.nil?
      count = category.topics.count
      if category.children.any?
        category.children.each do |children|
          count += children.decorate.topic_count
        end
      end
      count
    end
  end
  def post_count(category)
    unless category.nil?
      count = category.topics.count
      if category.children.any?
        category.children.each do |children|
          count += children.decorate.topic_count
        end
      end
      count
    end
  end
end

app/helpers/forum/replies_helper.rb
module Forum::RepliesHelper
end

app/helpers/forum/topics_helper.rb
module Forum::TopicsHelper
end

app/views/chunks/forum/topics/_item_reply.html.haml
.messages-item.reply{:id => "reply-#{reply.id}"}
  = link_to user_path(reply.user), :class => 'pull-left' do
    = image_tag reply.user.decorate.processed_avatar(size: 36),
          :alt => reply.user.decorate.processed_name,
          :class => 'img-thumbnail img-round tipb',
          :style => 'width: 36px',
          'data-original-title' => reply.user.decorate.processed_name

  .messages-item-text
    .meta.bg-cubs
      = link_to user_path(reply.user), :class  => 'user-link' do
        %span.fa.fa-user.fa-fw
        %strong= reply.user.decorate.processed_name
        \&nbsp;
      %small= l reply.created_at, :format => :long
      .pull-right
        = link_to "##{reply.id}", forum_category_topic_path(@forum_topic.category, @forum_topic, :page => params[:page], :anchor => "reply-#{reply.id}")
    .clearfix
    = reply.body.bbcode_to_html.html_safe
    .clearfix
    - unless reply.user.signature.nil?
      .messages-item-signature
        = reply.user.signature.bbcode_to_html.html_safe
      .clearfix
    .messages-item-buttons
      .btn-toolbar.pull-right
        - if user_signed_in?
          .btn-group
          .btn-group
    .clearfix

app/views/chunks/forum/topics/_item_topic.html.haml
.list-item.topic{:id => "topic-#{topic.id}"}
  .col-xs-3.col-sm-1.col-md-1.topic-user-avatar.text-center
    = link_to user_path(topic.user), :class => 'tipb', 'data-container' => 'body', 'data-original-title' => topic.user.decorate.processed_name do
      = image_tag topic.user.decorate.processed_avatar(size: 50), :alt => '', :class => 'img-round img-thumbnail'
  .col-xs-9.col-sm-11.col-md-7.topic-info
    %h4= link_to topic.title, forum_category_topic_path(category, topic), 'data-toggle' => 'popover', 'data-placement' => 'bottom', 'data-container' => 'body', 'data-trigger' => 'hover', 'data-content' => truncate(strip_tags(topic.replies.first.body.bbcode_to_html), :length => 200, :separator => ' ')
    .meta
      = link_to user_path(topic.user), :class => 'badge topic-author' do
        %span.fa.fa-fw.fa-user
        = topic.user.decorate.processed_name
      %span.topic-created.text-muted
        %span.fa.fa-fw.fa-calendar
        = l topic.created_at, :format => :short
  .col-md-4.hidden-xs.hidden-sm.topic-last-post
    = render :partial => 'chunks/forum/topics/last_post', locals: {last_post: topic.replies.last, topic: topic, category: category}

app/views/chunks/forum/topics/_last_post.html.haml
%span.badge.reply-count
  %span.fa.fa-fw.fa-comments
  = topic.reply_count
  \ответов
.clearfix
.info
  = link_to user_path(last_post.user) do
    = image_tag last_post.user.decorate.processed_avatar(size: 50), :class => 'img-round img-thumbnail'
    = "#{last_post.user.decorate.processed_name},"
  = link_to l(last_post.created_at, :format => :short),
  forum_category_topic_path(category,
  topic, :page => (topic.reply_count.to_f / Forum::Topic.default_per_page).ceil,
  :anchor => "reply-#{last_post.id}")

app/views/chunks/forum/topics/_reply_form.html.haml
= simple_form_for Forum::Reply.new, :url => forum_category_topic_replies_path(category, topic) do |f|
  .form-row
    .col-md-12
      = f.input_field :body, :as => :text, :class=> 'stmce'
      = f.input :user_id, :as => :hidden, :value => current_user.id
  .form-row
    .col-md-2
      = f.button :submit, :class => 'btn-success'